// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package type_builder

import baml "github.com/boundaryml/baml/engine/language_client_go/pkg"

type MessageClassView struct {
	inner baml.ClassBuilder
}

func (t *MessageClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *MessageClassView) PropertyRole() (ClassPropertyView, error) {
	return t.inner.Property("role")
}

func (t *MessageClassView) PropertyContent() (ClassPropertyView, error) {
	return t.inner.Property("content")
}

func (t *TypeBuilder) Message() (*MessageClassView, error) {
	bld, err := t.inner.Class("Message")
	if err != nil {
		return nil, err
	}
	return &MessageClassView{inner: bld}, nil
}

func (t *MessageClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}
