// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package types

import (
	"fmt"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/boundaryml/baml/engine/language_client_go/pkg/cffi"
)

type Message struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

func (c *Message) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "Message" {
		panic(fmt.Sprintf("expected Message, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "role":
			c.Role = baml.Decode(valueHolder).Interface().(string)

		case "content":
			c.Content = baml.Decode(valueHolder).Interface().(string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class Message", key))

		}
	}

}

func (c Message) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["role"] = c.Role

	fields["content"] = c.Content

	return baml.EncodeClass("Message", fields, nil)
}

func (c Message) BamlTypeName() string {
	return "Message"
}
