// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

var file_map = map[string]string{

	"chat.baml":      "// baml_src/chat.baml\n// 主对话 function\n\nclass Message {\n  role string @description(\"user, assistant, or system\")\n  content string\n}\n\nfunction Chat(messages: Message[], system_prompt: string) -> string {\n  client \"Gpt4o\"\n  prompt #\"\n    {{ _.role(\"system\") }}\n    {{ system_prompt }}\n\n    {{ ctx.output_format }}\n\n    {% for msg in messages %}\n    {{ _.role(msg.role) }}\n    {{ msg.content }}\n    {% endfor %}\n  \"#\n}\n",
	"clients.baml":   "// baml_src/clients.baml\n// LLM Client 配置\n\nclient<llm> Gpt4o {\n  provider openai\n  options {\n    model \"gpt-4o-mini\"\n    api_key env.OPENAI_API_KEY\n  }\n}\n\nclient<llm> Claude {\n  provider anthropic\n  options {\n    model \"claude-3-5-sonnet-20241022\"\n    api_key env.ANTHROPIC_API_KEY\n  }\n}\n\nclient<llm> Ollama {\n  provider ollama\n  options {\n    model \"llama3\"\n    base_url env.OLLAMA_BASE_URL\n  }\n}\n",
	"generator.baml": "// baml_src/generator.baml\n// Go 代码生成配置\n\ngenerator go {\n  output_type go\n  output_dir \"../baml_client\"\n  version \"0.220.0\"\n  client_package_name \"github.com/lixianmin/pc/baml_client\"\n}\n",
}

func getBamlFiles() map[string]string {
	return file_map
}
